focusconsulting/housing-insights

- docs/_includes/recent-blogs.html
- docs/_layouts/blog_post.html
- docs/_posts/2016-09-10-my-first-post.md
- docs/_posts/2016-10-20-second-post.md
- docs/_posts/2016-11-01-my-third-post.md
- docs/blog/index.html
Should resolve issue 6. Sidebar filters recent blogs for those other than current. Also adds author and date to individual blog posts.
> Resolves issue 6  and adds author/date to blog posts

- scripts/analysis/appraised_land_value_group_cluster.sql
Added sum of appraised land value grouped by cluster test.
> Added sum of appraised land value grouped by cluster test.

- docs/_includes/modal_email.html
> Adds data for forms to connect to mailchimp

- mockups/d3-scaffold/css/styles.css
- mockups/d3-scaffold/index.html
- mockups/d3-scaffold/js/d3-tip.js
- mockups/d3-scaffold/js/scripts.js
moves the d3 scaffolding from jsfiddle to a repo
> D3 scaffolding

- scripts/ingestion/make_draft_json.py
Removed previous pull request and re-created branch because things got messy. 
This script produces a JSON file per the first item in #54.
> Added JSON data loading script

- javascript/tool/building.html
- javascript/tool/css/building.css
- javascript/tool/js/building-map.js
Please see my comments in the file building-map.js for ongoing issues. This is still very much a work in progress!
> Added a simple Mapbox map to the building page.

- python/housinginsights/ingestion/make_draft_json.py
- python/housinginsights/ingestion/scrape_zoning_data.py
`cleaner_name` uses the SQL tablename + "_cleaner."
> Added cleaner name to make_draft_json.py

- javascript/tool/building.html
- javascript/tool/css/building.css
Adds hard-coded building header to the single building view.
> Added proof of concept for building header (hard coded)

- python/scripts/wmata_distcalc.py
See issue #106.  Updated output files to write to data directory.  Updated secrets.json to new relative path.
> updated paths for output files & secrets to match new code org

- python/housinginsights/ingestion/Cleaner.py
- python/housinginsights/ingestion/DataReader.py
- python/housinginsights/ingestion/SQLWriter.py
- python/housinginsights/ingestion/functions.py
- python/scripts/load_data.py
- python/scripts/manifest_sample.csv
- python/scripts/meta_sample.json
- Fixes bug for downloading the file from S3 when it does not exist locally.
- Adds ability to load the file directly from S3 without a local download. This should only be used when running on AWS directly (in the future)
> Fixes s3 automatic download when user doesn't have local data

- python/housinginsights/ingestion/DataReader.py
I wasn't able to test this as I haven't fully figured out how yet, and it doesn't look like a unit test is setup yet. But this could work, so try it out and let me know if it's close but needs some tweaks.
> Add method to create folder if it doesn't exist

- python/api/application.py
To finish off Issue #178. 
- neighborhood cluster: api/building_permits/nc total count of records in each unique neighborhood cluster 
ward: api/building_permits/ward
> Added flask endpoints for counts on ward & neighborhood cluster

- python/api/application.py
- python/api/requirements.txt
This is deployed to AWS and worked.
> Allows cross-origin GET requests to anything in the /api/* domain

- javascript/tool/js/rich-map.js
This is a pretty simple fix to the map load issue 206 that doesn't require promises or moving functions around in the code.
> Map load fix

- python/housinginsights/ingestion/DataReader.py
- python/housinginsights/ingestion/make_draft_json.py
- python/scripts/add_encoding_to_meta_json.py
- python/scripts/new_meta.json
This is my first PR so please be gentle - I believe I understand the DataReader classes and that this code will work. I did not think it necessary to implement a new __iter__ method on the DataReader class, but rather modified that method on HIReader.
Probably no need to keep the add_encoding_to_meta_json.py script but thought I'd share anyway.
I'm grateful for any feedback and happy to tweak further if necessary.
> Issue 169 encoding param

- docs/data/example.md
- docs/data/wmata_dist.md
- docs/data/wmata_info.md
- python/api/application.py
- python/housinginsights/ingestion/Cleaners.py
- python/housinginsights/ingestion/make_draft_json.py
- python/scripts/manifest.csv
- python/scripts/meta.json
- Adds the one-off version of the WMATA data tables (see #200 for next phase)
- Adds an API endpoint for nearby transit which returns both stops and routes that are accessible within a 0.5 mile walk.
> WMATA data and API endpoint

- python/api/application.py
Work in progress, but feel free to use as a starting point if you don't get any other PRs.  Unfortunately, I'm having a little trouble building the flask server, so this isn't even minimally tested.
> Haversine (issue 213)

- python/api/application.py
Deployed to live. Quick simple query for matching nlihc id
> Adds endpoint to deliver subsidies matching a given Nlihc_id

- python/housinginsights/ingestion/make_draft_json.py
Includes only the fix for resolving automatically adding 'unique_data_id' into the draft json file. #243 
This pull request only includes update to the make_draft_json.py.
> 243 unique data id fix

- python/scripts/manifest_sample.csv
- python/scripts/meta_sample.json
Fixes issue #246 by adding the table names to **meta.json** and **sample_meta.json**.
> Fix for issue #246

- python/api/application.py
- python/housinginsights/ingestion/functions.py
- python/scripts/load_data.py
- Added function to load meta.json into the database and call that from load_data.py
- Added api endpoint to serve meta to the front end
- Added optional command line argument to get API data from docker for testing purposes
As of 5/17 AM this has not yet been deployed to live site.
If someone's able to review this PR let me know! @ohaaga or @jasonrhaas or @jkwening
> Meta.json in the API

- docs/tool/js/util/filter.js
- docs/tool/js/views/filter-view.js
@ostermanj I was thinking about the ES6 issue this morning and took a crack at it. Turned out to be pretty easy to solve with a closure - I think the first time I've every actually understood how a closure works and needed to write one. So that's cool. 
While I was at it I went ahead and fixed up the state change events so that the util/filter.js code would trigger based on filter events. Looking at the logic with it hooked up though I realized we'll need to re-write most of the code so that we can use the same system of building up the logic based on the filter controls that have been added to the list, instead of hard-coding variable names. So for now I commented out the filter logic. @wassona we should discuss if it's best for you or John or I to take a stab at rebuilding the filter …
> Small additions to the filter logic

- docs/tool/css/styles.css
- docs/tool/index.html
- docs/tool/js/charts/donut-chart.js
- docs/tool/js/views/filter-view.js
- docs/tool/js/views/map-view.js
- docs/tool/js/views/results-view.js
- docs/tool/partials/map-view.html
Provides left and right sidebars that fly in and out, following the design team's mockup. Sidebars open by selecting option from subNav menu or by the open/close toggle (tab with triangle). Selecting the same option again closes the tray; selecting the other toggles which options are visible.
@NealHumphrey @thischrisoliver @ptgott
> Jo 248 fly in ui : layers & filters (left) and charts a & buildings (right)

- python/scripts/manifest.csv
- python/scripts/meta.json
1) Updated meta.json for the new fields in csv downloaded from opendata
2) Updated manifest.csv to point to new files for loading crime data. 
```
root@2bf0794abcca:/repo/python# python scripts/load_data.py rebuild docker
/repo/python/scripts/meta.json imported. JSON format is valid: True
Manifest table created in the SQL database
sql_manifest_exists: True
.........................>
crime_2015: preparing to load row 64 from the manifest
Content (MIME) type: application/vnd.ms-excel
File not found. Attempting to download file to disk: https://s3.amazonaws.com/housinginsights/raw/apis/20170524/crime_2015.csv
Download complete.  11864728 bytes downloaded.
Leading BOM (byte order mark) found in file 'crime_2015.csv'; updating header keys to omit BOM...
do_fields_match: True. meta.json and csv …
```
> Changes to ingest crime csv files from opendata

- docs/tool/js/views/map-view.js
Adds filter to mapView that responds to a filteredData state change. That's currently hard-coded to return three building IDs. This is on top of dev from one or two commits ago. The latest commits on dev give me 404s on some semantic utilities and don't provide the necessary filteredData state change.
> 273 jo filter project dots

- docs/tool/js/views/filter-view.js
- python/api/application.py
Also
- Alters the logic that builds the filter UI so that the list of variables is populated from the data available instead of hard-coded into the filterView.components
- Edits the API so that variables are no longer namespaced (this has been deployed to the API)
> Adds all filter variables requested in #236

- python/housinginsights/ingestion/Cleaners.py
- python/scripts/manifest.csv
- python/scripts/meta.json
Part 1 for https://github.com/codefordc/housing-insights/issues/180 - ingestion of census tract to ward and cluster population weights.
--------------------------
--------------------------
> 180-Added sql ingestion for census tract to ward/cluster weight mapping

- docs/tool/css/styles.css
- docs/tool/js/views/map-view.js
My apologies for the large number of listed changes.  A package on my text editor cleans up spacing in files I save, but plays hell with github's diffing (I've finally disabled the package).
The only lines I substantively changed are:
- lines 642-675 in map-view.js, and
- lines 214-224 in styles.css
These were just minor changes to makes the right panel a little bit nicer looking.
> Added styling to buildings list side-bar.

- docs/tool/css/styles.css
- docs/tool/index.html
- docs/tool/js/views/chloropleth-legend.js
- docs/tool/js/views/map-view.js
- docs/tool/partials/chloropleth-legend.html
The legend displays in the sidebar below the short description of the chosen overlay dataset.
> 317 Add a legend for the chloropleth maps

- docs/data/subsidy.md
- docs/data/topa.md
This PR provides some of the documentation outlined via Issue #316. 
I am working on documentation for the 'census' table and will submit that when it's ready (might not get to it until tomorrow or Tuesday though).
> PR for Issue 316 - documentation for subsidy and TOPA tables

- docs/data/census.md
@NealHumphrey I revised census.md to be more appropriate for non-technical audience per your comments. Also updated field listings to include alternative ACS fields for household income, and included notes on which fields were applicable only to certain years
> 335: updates to census.md documentation

- python/housinginsights/sources/wmata_distcalc.py
- python/scripts/meta.json
> Changes needed: Added use_cached_distance and database checks for walking distance for issues #313 and #312

- docs/tool/css/styles.css
- docs/tool/index.html
- docs/tool/js/util/filter.js
- docs/tool/js/util/polyfills.js
- docs/tool/js/views/filter-view.js
- docs/tool/partials/map-view.html
Adds the pillboxes. Here's a demo:
@ptgott or @ostermanj a quick review would be helpful! I'll be merging by end of day today so it'll be ready for demos before I leave, but a post-merge review to check for bugs still welcome.
> 344 pillboxes

- docs/tool/css/styles.css
- docs/tool/js/views/map-view.js
- docs/tool/partials/map-view.html
Opens the two side panels on first load for more obvious usage of the filter results panel while filtering, adds some helper wording above the filter results.
> 344 text cleanups

- docs/tool/css/styles.css
- docs/tool/js/views/filter-view.js
- docs/tool/js/views/map-view.js
- docs/tool/partials/building-view.html
I'll be pushing to this pull request while addressing smaller issues in #344 today.
> 344-Small Tweaks

- docs/tool/js/views/map-view.js
re: #350 
Animates only the projects that are entering or exiting based on the filters. Entering projects grow in size and then return to normal; exiting projects fade out.
Uses multiple mapBox layers to work, filtering on the basis of a new 'klass' property in the convertedProjects object. The klass ('enter','exit','stay', or 'none') is determined by comparing the current matches_filter boolean to the previous one.
Also gets rid of the confusing requestAnimationFrame method from before.
> Jo animate enter exit only

- docs/tool/css/styles.css
- docs/tool/partials/map-view.html
> Filter menu scrolls so that Divide By menu is always visible

- docs/tool/js/views/filter-view.js
This addresses #333 (though only partially!).
> 333-Clear only filters that have been touched in clearAllFilters

- docs/tool/js/core/housing-insights.js
- docs/tool/js/views/chloropleth-legend.js
- docs/tool/js/views/map-view.js
> 334 improve chloropleth legend

- python/housinginsights/ingestion/Cleaners.py
@NealHumphrey I think I've gotten them all now. The only one I couldn't figure out was pbca - which we don't seem to have any data to populate. Let me know if I missed something. For street view url some values were coming up as None in mar api call so I looked up the api and built a custom encoding based on lat/lon information available.
> 314 add geocode

- docs/tool/css/styles.css
- docs/tool/js/views/map-view.js
- docs/tool/partials/map-view.html
This is an update to #376 with some style changes to the circles and legend to unify the approach to entering/exiting circles via a darker border. For discussion in V2 planning.
> DEMO - tweaks to Jo color code matches

- docs/data/real_property.md
This pull request includes the documentation file I wrote for the real_property table.
> This is the documentation for the real_property_2017.csv file.:wx

- python/api/zone_facts_blueprint.py
- Replaces the current endpoint for census with a new zone_facts endpoint that can return any column from the zone_facts table
- alters the format of this endpoint slightly - next up will alter the front end to match
> Ready: 434 Slice zone facts

- docs/tool/js/charts/chart-prototype.js
- docs/tool/js/core/housing-insights.js
- docs/tool/js/util/filter.js
- docs/tool/js/views/dataChoices.js
- docs/tool/js/views/filter-view.js
- docs/tool/js/views/map-view.js
- docs/tool/js/views/results-view.js
Switches the URLs in the front end to use the new API, including code changes needed to follow newer format.
> 413 update api urls front end

- docs/tool/js/util/filter.js
- docs/tool/js/views/filter-view.js
So far I've added a quick 'if' block to filterData() to filter by location. Next I'll work on clearing the existing location filter when the user changes zone type.
> WIP 392 - Fix location filters 

- docs/tool/js/core/housing-insights.js
- docs/tool/js/core/router.js
- docs/tool/js/views/dataChoices.js
- docs/tool/js/views/filter-view.js
This pull request contains the changes to refactor continuous filters in #448 plus some first steps towards getting zone level data to reset with changing zones. Deploying to live to get updates into user test.
> 392 zone filters part of continuous

- docs/tool/js/views/filter-view.js
Resolves issue by using floor and ceiling for the min and max slider values respectively.
Also resolves (unreported) bug that decimal (i.e. percent) based data values were not working w/ slider.
Also provides cleaner slider behavior, wherein in between the min and max values the slider outputs values that are rounded to a reasonable number of significant digits (i.e. output is 23,100 instead of 23,128).
> Fixes sliders for min/max and percent-based values

- python/environment.yml
- python/housinginsights/sources/dhcd.py
- python/housinginsights/sources/models/dhcd.py
- python/requirements.txt
- python/scripts/get_api_data.py
Submitting this PR now to get it in; addresses issue #136....
--meg
> 136 DHCD DFD Pipeline

- python/housinginsights/sources/DCHousing.py
- python/housinginsights/sources/base.py
- python/housinginsights/sources/census.py
- python/housinginsights/sources/opendata.py
- python/housinginsights/sources/wmata_distcalc.py
- python/housinginsights/tools/logger.py
- python/housinginsights/tools/mailer.py
- python/scripts/get_api_data.py
Implemented centralized logging for get_api_data and individual source ApiConns.
Currently work in progress / proof of concept for logging. I will try to reach out to @NealHumphrey or @jkwening regarding the best way to test this - want to make sure it is safe to execute all of these functions locally without any unwanted side effects.
Next step is to think about sending out the logs to an admin. My initial thought is to pick up the full log file at the end of get_api_data, attach it to an email, and then archive that log (safer than deleting).
> WIP - Logging for get_api_data and sources

- docs/resources/onboarding/docker.md
Fixes the instructions for loading data using Docker.
Addresses https://github.com/codefordc/housing-insights/issues/384
> fix docker onboard to remove rebuild

- docs/data/subsidy.md
- python/scripts/meta.json
Minor updates to subsidy.md and updates to text descriptions for subsidy fields in meta.json.
> update subsidy doc and meta.json

- docs/tool/js/views/map-view.js
Addresses #476.
In the preview pane, makes the link more obvious by adding '>>' and underlining. 
For showProjectPreview, updated the display of null values by adding 
`| value == "null"`. Not sure how pervasive matching on `null` is versus `"null"` -- something to maybe check for in the future?
Thanks for introducing me to the project and helping me contribute!
> Made preview link more obvious, updated null matching

- docs/tool/css/filters.css
- docs/tool/js/core/router.js
- docs/tool/js/views/filter-view.js
Adds locations filters to the url encoding/decoding functionality. Also encodes/decodes mapLayer selections other than the initial setting, mostly so that decoding the location from a non-initial (ie non-Ward) zone type will work.
Re: issue #457
> Jo 457 url encode location

- python/housinginsights/ingestion/functions.py
- python/tests/test_functions.py
Added `get_unique_addresses_from_str` method in functions.py module.
The function takes an address string, parses the string, and returns a list of all
unique addresses based on the following delimiters:
- semicolon (;) - treated as delimiter for multiple unique addresses
-  'and' - treated as delimiter for multiple unique addresses
-  ampersand (&) - treated as delimiter for address number ranges
-  dash (-) - treated as delimiter for address number ranges
The function handles all potential composites of the delimiters noted above in a given address string. For processing composites, first handles 'complete' address delimiters (;, 'and'), and then address number range delimiters (&, -).
I intentionally did not include any address validation in this method because I feel that should be …
> WIP - Address table: one to many address

- python/housinginsights/ingestion/Cleaners.py
- python/housinginsights/ingestion/make_draft_json.py
- python/scripts/manifest.csv
- python/scripts/meta.json
Added parcel data to ingestion code.
Note - data for NL000414 uses "U" for parcel_x/y values instead of "N" for null. We should probably have this cleaned up in future updates from prescat.
> adds parcel data set to database

- python/housinginsights/ingestion/LoadData.py
- python/scripts/meta.json
- New entry in meta.json for building_permits_rate.
- Implemented _get_residential_units method for LoadData.
- Added field to input list for _populate_zone_facts_table.
> Added building_permits_rate to zone_facts table.

- python/housinginsights/ingestion/LoadData.py
- python/housinginsights/sources/DCHousing.py
- python/housinginsights/sources/base.py
- python/housinginsights/sources/cama.py
- python/housinginsights/sources/census.py
- python/housinginsights/sources/dhcd.py
- python/housinginsights/sources/google_maps.py
- python/housinginsights/sources/mar.py
- python/housinginsights/sources/opendata.py
- python/housinginsights/tools/mailer.py
- python/scripts/get_api_data.py
- python/scripts/services.py
Initial work to allow running of get_api_data and load_data as services from the application.
Issue #470.
> WIP - Improve logging, error handling, add services

- docs/tool/index.html
- docs/tool/js/util/exportCsv.js
- docs/tool/js/views/map-view.js
- docs/tool/partials/map-view.html
All changes from #499 are now added **_EXCEPT_** displaying the filter criteria in the modal. Will still add that (but wanted to start the pull request to give the option of merging now).
> 499 export csv additions (except filter criteria displayed)

- python/scripts/meta.json
I started updating the meta.json display text fields but did't get past building permits and crime. Hopefully this is along the lines of what @emkap01 was thinking.
> meta.json updates display text updates

- docs/data/affordable-housing-inventory.md
- docs/data/census.md
- docs/data/wmata_dist.md
- docs/data/wmata_info.md
- docs/data/zone_facts.md
@NealHumphrey this PR addresses the general 'update data documentation for all tables currently in the database' requirement from Issue #501.  Feel free to hack away at these as you see fit, my intent was just to try and cover some of the basics.
Most of the Markdown files that needed work should be in pretty good shape by this point, so next I will turn my attention to whatever values we may still be missing in the `display_text` key for each dictionary.  Will make sure to deconflict with @louvis.
> Minor updates to documentation for select tables in prod db

- docs/_layouts/datasource.html
- docs/js/datasource.js
[work in progress]
fixes https://github.com/codefordc/housing-insights/issues/530
Needs a bit of styling, but I can't commit to doing it.
Done at CodeForDC hacknight :)
> Add simple table for each datasource

- docs/tool/js/views/filter-view.js
All 3 categorical input elements are sorted alphabetically before dropdown list elements are added to the page
> Categorical sorting

- docs/tool/css/styles.css
- docs/tool/js/views/dataChoices.js
- python/api/filter_blueprint.py
The API changes in this have been deployed already
> Adds additional fields to the filter data set.

- python/scripts/meta.json
I went through and added some more display_text values and tried to standardize what I had entered along with existing entries. The one table I didn't finish that I worked on was dc_tax because there are some fields that I can't find a good reference for.
> updated meta.json display_text fields

- docs/tool/js/views/project-view.js
- docs/tool/partials/project-view/header.html
Uses address string. Some may come up without images, but nearly all seem to be working from sampling around.
> Adds streetview to project view

- docs/tool/js/views/dataChoices.js
Per discussion this evening, I updated dataChoices.js with a `sourcetable` key per dictionary, and then populated the value for each key with the corresponding table from which that value is derived.
> updated dataChoices.js with 'sourcetable' field for each dictionary

- docs/tool/js/core/router.js
Fixes the encoding mistake leading to path ending in #/HI. Also provides decoding backstop just in case that crops up again.
RE #535
> Fixes path #/HI problem

- python/housinginsights/ingestion/LoadData.py
- python/scripts/meta.json
- Adds two new entries to meta.json for project table.
- Adds code to _populate_calculated_project_fields() for LoadData.
- Comment explains how bus_routes_nearby still could be updated more efficiently.
> Adds nearest_metro_station & bus_routes_nearby to project table.

- docs/_layouts/blog_post.html
- docs/_layouts/datasource.html
- docs/_layouts/home.html
- docs/_layouts/insight.html
- docs/_layouts/main.html
- docs/_layouts/toolLayout.html
Oops. Called it 'header' instead of 'head', which made the browser try to correct the DOM by adding an extra body above it.
> Fixes incorrect head/header syntax

- docs/tool/css/styles.css
- docs/tool/js/core/router.js
- docs/tool/js/views/filter-view.js
- docs/tool/js/views/map-view.js
* Changes date filter  format to mm/dd/yyyy
* Adds note to that effect
* Validates that dates put in the text boxes are valid and within range
* Alerts user if an input is invalid
Also:
URL decoding was sometimes happening before the `filterControlsDict` was defined. 
* Adds gate function to check multiple states before initializing URL decoding.
> Date input validation / alerts;  decode url fixes

- docs/tool/css/styles.css
keeps subnav on project view stuck to the top. Sidebar nav is not ideal b/c it doesn't have the top part you'd expect once you scroll it down, but good enough for now.
> fixes subnav that was covering project view

- docs/tool/js/core/router.js
- docs/tool/partials/map-view.html
> Remove building preview form url when deselected; fixes typo in modal

- docs/data/index.md
@NealHumphrey I noticed while reviewing the tool this evening that we never updated the main documentation page (my fault for dropping the ball on that after we discussed it the other week).
Per our discussion, I finished listing all the sources we use.
> main documentation page now complete

- docs/_includes/header-includes.html
Should have done this earlier, didn't realize it hadn't gotten in there. @mkalish heads up, would be good to check that this is working after it's deployed to master
> Adds google analytics to the whole site

- docs/tool/js/views/map-view.js
- docs/tool/partials/map-view.html
Fixes a variety of bugs for the assets feature
> Feature assets on mapview

- docs/tool/js/views/filter-view.js
- docs/tool/partials/map-view.html
Small UI changes to the filter sidebar
> Feature small ui tweaks

- docs/tool/js/views/map-view.js
Use the washington-metro icon
Default to a larger icon for assets
> Use washington-metro icon and update icons to be larger

- docs/_includes/header-includes.html
- docs/tool/js/views/filter-view.js
Adds zoom to address when no project matches
> Feature: Zoom to address when no project matches

- docs/_includes/navbar.html
- docs/tool/js/views/filter-view.js
Add updated date and fix zoom to address zoom level
> Feature add updated date

- docs/_includes/navbar.html
- docs/_includes/tool-footer.html
- docs/_includes/tool-header.html
- docs/index.html
- docs/tool/delete-after-test/building.html
- docs/tool/index.html
- docs/tool/js/core/housing-insights.js
- docs/tool/js/views/project-view.js
Re-arranges the page on the site such that the tool is now the home page and the current home page is moved to /about
> Move /tool to the index and create /about

- docs/_includes/navbar.html
- docs/tool/js/views/project-view.js
- Updates for the December catalog
- Fix the display of manager
> Feature: December update and fix manager on project page

- docs/_includes/navbar.html
- docs/index.html
- Update for the february prescat export
- Replace get involved section with simple mailto form
> February 2021 updates

- docs/tool/js/views/filter-view.js
Updating the geocoding for missed addresses to use the mapbox API
> Chore: use the mapbox geocoding api

- docs/tool/partials/map-view.html
- python/Dockerrun.aws.json
- python/environment.yml
- python/requirements.txt
- Removes the maintenance message
- Fixes the SQLAlchemy dependencies for postgres 12
- Adds the now required Dockerrun.aws.json file
> Oct 2021 update
