focusconsulting/housing-insights

scripts/preprocessing/load_data.py, scripts/preprocessing/load_manifest.csv
Building permits data **has** been loaded into the AWS database. No need to re-run
Solves:
- Low Memory error that showed up in the read_csv method
- Non-printing characters at the start of the file (i.e. in the header name of the first column) now removed
=> Adds the Building Permits data set to the manifest, and fixes a couple loading issues

docs/css/prototype-1a.css, docs/d3-mockup/index.md, docs/d3-mockup/js/prototype-1a.js
I've done a bit of work on making the moving block chart prototype page resemble the original [mock-up](https://app.moqups.com/neal@nhumphrey.com/zeZOXaXpNx/view/page/abd7c6e09?ui=0). So far, I've focused on creating a 'METRICS' menu that changes the field of the block chart. In producing the menu, I've made some design decisions that probably have better alternatives. I've summarized them below. Let me know what you think and feel free to revamp.
1. I'm okay with the 'without extend prototype' branch, but have put off incorporating it in case it's still something we're talking about.
2. I've added the Metrics menu to 'prototype-1a.js'. If this file was intended only for testing out the d3 functionality (rather than implementing the mock-up in general), I'd be happy to move the …
=> Re: Issue 52 - add metrics menu

javascript/tool/js/building-map.js
In the building page, I'm working on a way to grab data for Mapbox maps. As shown in the building page prototype, we're displaying various layers of data (probably geoJSON) on Mapbox maps: layers of public transport, other public housing, building permits and so on. I was thinking of using app.getData() to do this, grabbing the .csv files that we use for Charts and manipulating the data into geoJSON (if it's not in that format already). This way, I could add geoJSON layers to Mapbox maps while sharing data with any other Charts that needed it. 
There's a possible issue here: the parameters of app.getData() currently assume that we will be using the data for a Chart. In the comments I've suggested two possibilities, either (a) adjusting app.getData() to work with both Charts and Mapbox …
=> Adding the beginnings of code for feeding building data into Mapbox maps for the building page

javascript/tool/building.html, javascript/tool/js/building-map.js
@NealHumphrey @vincecampanale @wassona @ostermanj 
I've added a grabData() function that requests geoJSON from data sources specified in a 'datasets' object literal. A setInterval() function waits for all responses to come back, then assigns the geoJSON to the 'data' keys in the 'datasets' object, and calls a prepareMaps() function that produces the Mapbox maps.
Doing this created issues with scope in defining layers in the MapboxPortal constructor, so I've moved all layer definitions to prepareMaps(). Now MapboxPortal simply iterates over all the layer IDs passed to an argument as an array of strings.
I've also added a 'buildingForPage' object literal as a placeholder for whatever way we decide on to bind data about a selected building to the information page.
At the moment, there is an …
=> Handle multiple data sources in the building information page

javascript/tool/building.html, javascript/tool/js/building-map.js, javascript/tool/js/geo-distance.js
#80 
@ostermanj @wassona @vincecampanale 
Since the text of the map-related accordion panels in the building page prototype has to do with features near the target building, I've copied some code from a library for geospatial calculations to assign distances to a given Mapbox source and list those distances next to the relevant map.
A big difference from the prototype is that this code calculates geospatial distance to nearby metro stations, whereas the prototype shows walking distance. While the calculations of geospatial distance use snippets of a JS library copied to a file in the 'js' folder, I imagine calculating walking distance will involve some asynchronous API calls to, say, Google Maps. This can be something to look into later!
=> On the building page, list nearby features

python/environment.yml
Removed the last bits of the versions for things that were not in the osx64 channel.
I also had to remove vc & vs2015 entirely since no versions are in the osx64 channel at all.  I was able to run the load_data script without them so hopefully they aren't necessary...
@NealHumphrey
=> updating env yml for mac

python/housinginsights/ingestion/DataReader.py
though doesn't address the root cause that different files can have different encoding. See issue #169 for next steps.
@prisalex and @louvis  and @emkap01  and anyone else that has a Mac, this should fix the problem of not being able to build the Docker database. Let me know if it doesn't!
=> Fixes encoding issue on Mac,

docker-compose.yml
Fixes the docker-compose race condition by re-trying in the event of a failure.  However, the retries are bounded (10 for web, 3 for postgres) so that if there is an actual problem with a configuration, it will still fail as expected, rather than retrying infinitely.
=> Fix docker-compose race condition Fixes #173

python/tests/test_make_draft_json.py
Added some units tests for the `make_draft_json.py` file.  There are still more tests that can be added to the `test_make_draft_json(self)` and `test_make_all_json(self)` methods, but this is a good start.
Running the full ` nosetests --verbosity=2 --with-coverage --cover-inclusive --cover-erase tests` command doesn't work because there is an import error in the `test_ingestion.py` file.  This needs to be fixed.
However, the tests I added pass when running individually.
`nosetests -v tests/test_make_draft_json.py -v`
```
nose.config: INFO: Ignoring files matching ['^\\.', '^_', '^setup\\.py$']
TODO:  Still needs more tests. ... ok
TODO:  Still needs more tests. ... ok
test_pandas_to_sqal_data_type (python.tests.test_make_draft_json.TestMakeDraftJson) ... ok
test_sql_name_clean …
```
=> Add make_draft_json unit tests

api/app.py, python/environment.yml, python/requirements.txt
Added simple Flask API for doing basic SQL queries.  The included endpoints are:
- `/api/<table>`.  this returns 100 rows from the table chosen.  If the table does not exist you will get a 404 error.  I did 100 to start because the database is too big to return everything at once.  We need to implement pagination.  Flask-SQLAlchemy and Flast-RESTless comes with this built in, so if we move to that we get this for free
- `/api/building_permits/<zipcode>` .  Returns the number of table entries given a zip code.
- `docker-compose up -d`
- `cd api`
- `python app.py`
- Go to http://localhost:5000/api/table to see the JSON output.  For example http://localhost:5000/api/building_permits or http://localhost:5000/api/crime
- Go to http://localhost:5000/api/building_permits/zipcode to see the …
=> Added simple Flask API for doing SQL queries

python/api/application.py, python/api/requirements.txt, python/scripts/meta.json
Adds two endpoints to the API, one for nearby_projects and one for nearby_building_permits that use a lat/lon param to calculate the building permits within X miles. 
This also implements a couple changes to how jsonify writes json, to resolve some issues related to data types that this endpoint highlighted. 
This is deployed to the live site
TODO in a refactor we'll want to eliminate duplicative code
=> Add permits and projects w/in distance

javascript/tool/css/map.css, javascript/tool/js/pie.js
This changes how the pies are drawn: one data-bound arc for % yes on top of a static background instead of two data-bound arcs. That makes the code simpler, especially for the transitioning (animating) the arcs when selecting a different zone type or zone.
Adds the neighborhood (cluster name) data to the drop down when the neighborhood map layer is selected. All but the Zillow layer are connected to the pie charts— @NealHumphrey for the demo beware that selecting Zillow does nothing to the pie charts. Disable it?
@nealfwilliams @ptgott
=> Animates pies on load and update; cluster names in the pie chart dropdowns

javascript/refactoring_sandboxes/option1/chart_types.js, javascript/refactoring_sandboxes/option1/data_objects.js, javascript/refactoring_sandboxes/option1/user_selection_components.js, javascript/refactoring_sandboxes/option1/views/building_view.js, javascript/refactoring_sandboxes/option1/views/map_view.js, javascript/refactoring_sandboxes/original_structure/PubSub.js, javascript/refactoring_sandboxes/original_structure/accordion.js, javascript/refactoring_sandboxes/original_structure/building-chart.js, javascript/refactoring_sandboxes/original_structure/building-header.js, javascript/refactoring_sandboxes/original_structure/building-map.js, javascript/refactoring_sandboxes/original_structure/d3-tip.js, javascript/refactoring_sandboxes/original_structure/geo-distance.js, javascript/refactoring_sandboxes/original_structure/housing-insights.js, javascript/refactoring_sandboxes/original_structure/moving-blocks.js, javascript/refactoring_sandboxes/original_structure/pie.js, javascript/refactoring_sandboxes/original_structure/rich-map.js, javascript/refactoring_sandboxes/original_structure/subsidy-timeline.js
#212 
I've also begun (like, super-preliminarily) to translate the whiteboard sketch into constructor declarations and .js files within the 'javascript/refactoring_sandboxes/option1' directory. 'javascript/refactoring_sandboxes/original_structure' takes you to a version of the dev branch's 'javascript/tool/js' directory in which everything but the main constructor, function and variable declarations have been taken out.
Let me know what's useful or not here and I can keep plugging away at it. 
I see this as more of a communication tool than an actual version of the code. For alternative structures, we could add other 'option' directories. It's less efficient than using git branches but lets you have the same file from each variation open in your editor.
=> Add a new directory for high-level refactoring options and discussion

python/requirements.txt
When attempting to build the necessary Python harness virtualenv environment on a recently updated copy of ArchLinux using Python 3.6, I encounter the following error.
`Double requirement given: psycopg2 (from -r requirements.txt (line 19)) (already in psycopg2==2.6.2 (from -r requirements.txt (line 8)), name='psycopg2')`
This removes the extraneous, double declaration of the psycopg2 adapter, favoring the general one for the pegged version one. I was then successfully able to build the virtual environment as needed.
Reviewing tickets currently open makes it seem this might be generally know to be an issue associated with Docker and deployment, for instance mentioned in #154.
=> Fix double declaration of psycopg2 in requirements.txt

python/housinginsights/sources/mar.py, python/tests/test_mar.py
@NealHumphrey I fixed incorrect reference when mar.py was refactored to inherit from BaseApiConn. In addition, added a new method for reverse look up using latitude and longitude, and added test_mar to avoid similar scenario moving forward.
=> 262 - Issue in mar.py after refactor

python/housinginsights/ingestion/Cleaners.py, python/housinginsights/ingestion/DataReader.py, python/scripts/meta.json, python/tests/test_DataReader_bom_handling.py, python/tests/test_data/manifest_bom_handling.csv, python/tests/test_data/meta_bom_handling.json
Modified `DataReader` class to handle byte order marks (BOMs) in data file headers, currently only found in opendata.dc.gov-sourced files (actually served from opendata.arcgis.com).  Ran tests on the dc_tax and building_permits data files.  (Ref: [Issue #133 comment](https://github.com/codefordc/housing-insights/issues/133#issuecomment-299519507))
After this merge, all opendata.dc.gov data files with BOMs no longer need to have the byte order mark manually stripped before uploading to the AWS S3 bucket.
Ref changes in `DataReader` class:
[Modifications to `download_data_file(...)`](https://github.com/dogtoothdigital/housing-insights/blob/dev/python/housinginsights/ingestion/DataReader.py#L198-L213)
[Addition of `_remove_bom_from_file(...)` and …
=> 133 bom removal in opendata dc gov file headers

python/api/application.py, python/api/environment.yml
Github flagged a bunch of lines for the diff, but they all appear to be related to white space.  The actual change I made is just to add lines 92-123.
Longer term we would want to make this endpoint return a table in our database, as opposed to a query with two joins, like it is now.  However, this should work fine, for now.  
This query will have to change as we add filter criteria, but this query provides the data we agreed to filter on in this sprint.
Also added a yml file to create a conda environment.
=> Added an endpoint to return the JSON for filtering.

python/housinginsights/sources/opendata.py
From opendata - 
> The live data feed for this layer was incorrectly pointing to the last 30 days source. The Crime 2017 layer has been corrected. You should now see data starting in January through today. Thank you for bringing this to attention and appreciate your participation in Open Data DC.
=> Fix crime 2017 data file url to link to right file

docs/tool/css/styles.css, docs/tool/js/charts/chart-prototype.js, docs/tool/js/charts/donut-chart-OLD.js, docs/tool/js/charts/donut-chart.js, docs/tool/js/charts/pie-chart-proto.js, docs/tool/js/core/housing-insights.js, docs/tool/js/views/map-view.js, docs/tool/js/views/results-view-OLD.js, docs/tool/js/views/results-view.js, docs/tool/partials/map-view.html
— Two donut charts instead of four
— Connected to filterData event
— First shows percentage of buildings matching the filter(s)
— Second shows the percentage of total units represented by the buildings matching the filter(s)
The last commit puts the charts in the buildings pane and removes the charts pane. With only two charts, it seems unnecessary to have a separate pane for them. And these charts work really well here, animating their change at the same time the list is shortened or lengthened.
If you prefer keeping the charts pain, revert to the second to last commit.
=> Jo connect charts to filters

docs/tool/css/filters.css, docs/tool/js/views/filter-view.js
This has to do with issue #317. There are a few things to note:
1. The 'clear filters' button clears the filters by calling a 'clear' method on each filter-related UI component, which I've extracted into a constructor. This is because the control of the filter values is tied to the state of the UI components. This means that resetting the UI components and resetting the filtered values is one and the same move.
2. There's already a 'reset zoom' button in the center-top of the map view, and I didn't want to interfere with this. As a result I've based the Clear Filters button on the deletable labels that appear in the SemanticJS dropdown menu, adding the option to clear the filters to the filter tab itself. If there's a more intuitive option, I'm okay with us changing it.
3. For some …
=> 317 clear all filters

python/api/application.py, python/housinginsights/ingestion/Cleaners.py
This both adds the census weighting factor and expands our ability to do slicing and dicing of any 'observation' based table (i.e. where each record is some sort of unique item, like building_permits or crime). 
- Fixes bug where census_tract 1 was being ommitted due to Cleaner expecting the manually downloaded file format as opposed to currently-used API download format. Manually downloaded file had 2 header rows, api version has 1
- Adds flexible function for `census_with_weighting` that returns the weighted count of any census field in the 'items' format that can be sent straight to the json output
- Replaces the 'count_all' endpoint with a 'summarize_observations' endpoint. This one has significantly more flexibility including filtering of records (e.g. only violent crime or only …
=> 180 census weighting plus crime count filtering

docs/tool/js/core/housing-insights.js, docs/tool/js/util/polyfills.js, docs/tool/js/views/chloropleth-legend.js, docs/tool/js/views/filter-view.js, docs/tool/js/views/map-view.js, python/api/application.py, python/api/requirements.txt
- Adds a finalized list of demo layers to the view, and fixes various logical bugs needed to make different types of data work (percents, missing values, etc.) 
- Adds number formatting for various data types to legend (percent, $, commas)
This messes up the 'one less' logic for the max of a range (e.g. 0 to 499, 500-999) and instead uses the same number for top of one range and bottom of the next one. Had to switch it because the "minus 1" logic failed for percents. Put a TODO to fix this. 
Again @ptgott or @ostermanj would be great to get a review, though I'm going to go ahead and merge as it gives us a bunch of needed functionality for user tests.
=> 344 add layers to view

docs/tool/js/views/filter-view.js, python/api/application.py
- Fixes acs median rent filter
- Renames / rearranges some of the filters to put all location elements at the top and others below.
@ptgott heads up that this fix is deployed to the API, so the median rent is back. Can uncomment it in yours. 
Unfortunately this is only a partial fix for right now though. We need a better way to handle null values - some of our projects we don't have a value for the neighborhood rent, so this still show up in the results when you filter to a low max but with the min still at 0. We've discussed adding an 'include nulls' checkbox to make this choice explicit. 
@txomashernandez Heads up in case any user testers notice the odd behavior with the neighborhood rent field - it's the nulls that are still included.
=> Fixes acs median rent filter

docs/data/building_permits.md, docs/data/crime.md, docs/data/opendata.md, docs/data/tax.md
This PR contains new documentation for several data sources (all from DC OpenData) as part of the effort led by @emkap01.
OpenData.md has general information on the DC OpenData initiative, and each source has its own .md file that links back to it. I'm new to the way internal markdown links work, so I am hopeful that I did them correctly.
Hope this is helpful! Happy to expand further as needed.
=> Ready: Adding documentation for OpenData sources

docs/tool/js/views/map-view.js
I wish all fixes were so easy. mapBox addLayer method can specify which layer the new added one should be before. The line now specifies "projects." Overlays now all underneath projects so long as the project layer is loaded before someone selects an overlay. That should be the case.
=> Puts overlay layers below the project layer so that circles are always on top.

docs/tool/js/views/map-view.js
I forgot to remove a superfluous 'var' declaration in map-view.js. I've done so here.
=> 334-very minor tweak

python/housinginsights/ingestion/Cleaners.py, python/housinginsights/sources/base.py, python/housinginsights/sources/models/pres_cat.py
Added methods to Cleaner module so that geographic zones in project table are encoded with data instead of nulls. I utilized api calls to MAR and added a cluster_desc_map dictionary object to prec_cat model. Since I was doing MAR api calls I also populated status for buildings that are unique with respect to those available in the prescat - that is, those that don't have a matching nlihc_id.
=> 314 add geocode

docs/tool/js/views/map-view.js
re issue #397 
Subscribes to filteredProjectsAvailable state change; calculates bounding box of matching projects and zooms to fit the bounding back. mapBox, FTW, includes a `fitBounds()` method that handles this.
Includes workaround for issue #405 that can be removed when that issue is resolved.
=> Map zooms in response to filtered projects

python/housinginsights/ingestion/LoadData.py, python/tests/test_load_data.py
1. Added a function that runs after all data loading is completed that drops the existing records from the zone_facts table and rebuilds the table.
1. Includes function that generates the values used in zone column ensuring that they match the relevant standard column name and zone_specific match the value for that column that is used in other tables.
1. Populate the zone_facts table with calculated fields from the "census_with_weighting" api endpoint: 'poverty_rate', 'fraction_black', 'income_per_capita', 'labor_participation', 'fraction_foreign', 'fraction_single_mothers'.
I need to complete unit test code so it is more robust.
To test:
- simply rebuild the database by running `python python/housinginsights/ingestion/LoadData.py docker` - assuming your currently at the …
=> WIP: 388 zone facts table

docs/tool/js/views/map-view.js
This is a small addition to merged PR #408. The map initially loads according to hard-coded originalCenter and originalZoom variables; those settings are now overwritten after the first `zoomToFilteredProjects` takes place (after initial projects load), so that the settings will be adapt to potential project additions in the future.
=> Resets originalCenter and originalZoom after the first zoom to projects.

docs/Gemfile.lock, docs/tool/css/filters.css, docs/tool/css/styles.css, docs/tool/js/views/filter-view.js, docs/tool/partials/map-view.html
This PR also animates the 'clear filter' labels to fly from their associated UI components to their place among the other 'clear filter' labels. The aim here is to make it unmistakable that the orange labels emerge as a result of choosing filters, and that they move to the top of the Data Choices menu. 
Addresses #393
=> 393 - Place 'clear filter' labels at the top of the Data Choices menu

python/housinginsights/ingestion/Cleaners.py, python/housinginsights/ingestion/LoadData.py, python/housinginsights/ingestion/functions.py, python/scripts/meta.json
I made some modifications which allow for the topa cleaner to verify existence of a record in the project table with a given address id (MAR id). It was a bit trickier than expected.
Given this functionality, I am not sure about next steps. My notes say that we want to add a new field called nlihc_id to the topa table and populate it if it exists, but wouldn't it just be a duplicate of the existing address_id? Perhaps a boolean field would be better so as not to duplicate data? I'm afraid I don't understand how the field will be used.
This PR is currently stable - so I am happy to keep working with further guidance, or to hand off to someone to polish off (I do think the remaining work should be the "easy" part).
Thanks as always.
=> Add nlihc_id to topa table #404

python/housinginsights/ingestion/LoadData.py, python/scripts/load_data.py, python/scripts/meta.json
Adds the functionality to have calculated fields in project table during updates of the database. Implements this for the 'most recent reac score'. Relevant to both #425 and #430. 
My only concern so far is maintaining the messy SQL statements required to extract the relevant data from the partner tables. I tried to implement the automap function so that I could try to use SQLAlchemy syntax, but I didn't see a way to then actually use that to do the stuff I wanted to. Straight SQL seemed easier to implement. 
At a minimum we could break each field update into a separate method - at the moment I have comments to designate sections of the _populate_calculated_project_fields code, but the could be methods that are listed out one by one just to break up teh code a bit. 
@jkwening especially …
=> 430 calculated project fields reac

docs/tool/js/core/housing-insights.js, docs/tool/js/core/router.js, docs/tool/js/util/filter.js, docs/tool/js/views/dataChoices.js, docs/tool/js/views/filter-view.js
This pull request includes a variety of changes to the filterControl elements, primarily for continuous controls but also for date controls, and to the connected filter.js, router.js. Note that this PR also includes #448 which did some simple rearrangment of the continuous filter. Included:
- Any continuous control can have its min/max values reset at any point. 
- Zone-based continuous filters have their values cleared and min/max values reset whenever the zone type is changed. 
- Rearranges how values of the UI components (checkbox, textbox, slider) are bound together. If adjusting one of the UI components, the new state is determined by what is currently in the other UI components. This way if the internal state somehow gets out of sync with the UI state, it will self correct whenever …
=> 392 zone filters + continuous and nulls refactor

docs/tool/js/core/housing-insights.js, docs/tool/js/core/router.js, docs/tool/js/views/filter-view.js
Our filter components, and their links to the state module, have gotten complicated. The continuous filter is the most complicated, as it has text boxes, null checkboxes, sliders, and associated states for all of these. 
I'm trying to refactor this code to make it a bit easier to follow, in preparation for (manually) pulling in the code for #444. This PR is mostly rearranging the order of the code in the continuousfiltercontrol setup function so that code that is related to each other appears side by side, plus the addition of some code comments. Making this a separate PR so that the manual additions of #444 are clearly differentiated from this rearrangement.
=> Refactor continuous filter

docs/tool/js/views/filter-view.js
Addresses first bug listed in issue #442 .
Pillboxes and URL encoding clear when date and continuous filters are set back to their original settings. Works on sliders, checkbox, and text inputs.
=> Jo 442 filter ui bugs

python/housinginsights/ingestion/Cleaners.py, python/housinginsights/ingestion/LoadData.py, python/housinginsights/ingestion/SQLWriter.py, python/housinginsights/ingestion/make_draft_json.py, python/scripts/manifest.csv, python/scripts/meta.json, python/tests/test_Cleaner.py, python/tests/test_data/manifest_load_data.csv, python/tests/test_data/meta_load_data.json
- Fixed bug causing --update-only to fail in LoadData.py
- Added cleaner step that geocodes the census_tract of building permits.
Due to size of building permits data needed to improve processing time. For 2016 data file, there's 47k rows with ~37k unique buildings. It was taking 45+ to process and that's if it didn't time out  - I was able to process without issues during evening hours.
Implemented concurrency since the bottleneck was an IO issue - api calls and we don't care the order in which we write the data rows to the psv file for database upload. 
It is currently using a max of 100 threads to process and clean all the rows for a raw data file. This improved processing time considerably - went from 45+ mins to 5-7 mins (398s last night, 329s early this morning).
- Using threading …
=> WIP -   437 building permit update

python/housinginsights/ingestion/LoadData.py, python/housinginsights/ingestion/SQLWriter.py, python/scripts/load_data.py
Provides 2 ways for a table to be dropped (along w/ associated sql manifest rows) when updating the database. This allows for the addition/removal of columns while updating a single table, instead of only being able to do so by rebuilding the whole database. 
Also includes a few try/except blocks for the zone_facts table. Add logging.error when a field could not be found/calculated due to missing data - this means the rebuilding of the database will still work even if a necessary table (building_permits, census, etc. ) is missing. Allows for faster testing of things that only apply to certain sections of the database b/c you can add 'skips' to any tables you're not currently working on.
=> Remove table during update

docs/tool/js/views/filter-view.js
Addresses #333 
The former had tried to match the string return value of the text inputs with the numeric return value of min/maxDatum.
The latter had tried to use an equivalence operator on JS Date objects, which can't be done. I've used the operator on the valueOf() those Dates instead.
Now only 'touched' filter controls should clear.
=> 333 Fix ContinuousFilterControl.isTouched() and dateFilterControl.isTouched()

docs/tool/js/views/map-view.js
Addresses #394 
This PR simply duplicates the setTimeout code for filtering in projects in map-view.js, but for the 'project-exit' layer.
=> 394 Project exit animation

docs/tool/css/styles.css, docs/tool/js/views/filter-view.js
Addresses #396 
1. Adds placeholder text to the input boxes within the Semantic UI dropdown menus for the categorical filters. 
2. Explicitly specifies the 'overflow' CSS of the container for categorical filter components. This may not be necessary, given the 'visible' is the default value for 'overflow' anyway, but I wanted to ensure that the container wouldn't be rendered with an overflow of 'scroll'.
=> 396 Make very small changes to the categorical dropdown menus

python/api/project_extended_constructor.py, python/application.py
hat currently have an nlihc_id. Currently this means that the `topa`, `subsidy`, `real_property` and `reac_score` tables are now available on the project endpoint whenver you request the data for a specific nlihc_id. For performance reasons the data from these tables are not added to the json when a list of all projects is requested.
- Adds sql-injection protection to this endpoint
To test:
- Spin up server with `python application.py`
- visit localhost:5000/api/projects/NL000196
Deployed to live server
=> Adds nested JSON data for one-to-many tables in project endpoint

docs/tool/css/styles.css, docs/tool/js/core/router.js, docs/tool/js/util/filter.js, docs/tool/js/views/dataChoices.js, docs/tool/js/views/filter-view.js, docs/tool/partials/map-view.html, python/.elasticbeanstalk/config.yml, python/api/filter_blueprint.py, python/api/project_extended_constructor.py
Adds a searchbar to the top navigation, and adds two filter categories of project name and project address to the left sidebar. The searchbar uses a combined name/address field called 'proj_name_addre' which has been added to the API for the /filter and /projects endpoints. This has already been deployed to the live API so that this functionality can be tested w/out spinning up a local api server and swapping urls. 
The search bar is a re-styled combo search/dropdown box, the same one we use for categorical data choices, and behaves like a regular filter control - this seemed like the fastest way to get a basic search functionality integrated into our current workflow. One downside is that it doesn't produce true 'search results' like a user might expect, rather it provides instant …
=> 472 search for project

docs/data/affordable-housing-inventory.md
@NealHumphrey this is a first crack at cleaning up the documentation for the projects table. All I did was update the description of the different datasets that we use to build the table, since the Markdown file was out of date by several months.  
I added context per dataset based on whatever notes I could find in the relevant Issues, and also removed all hyperlinks to individual Issues (on the assumption that when users of the tool actually call up the documentation from the front end, they will neither need nor want to see the underlying Issues).
It would probably be worthwhile to add more language in here that explains the business logic behind how we dedup projects across datasets, but I will defer to you and/or @jkwening for that since a) much of that logic is baked deep down into …
=> cleaned up documentation for projects table

docs/tool/css/styles.css, docs/tool/js/views/filter-view.js
RE issue #490 : Active filters are darker orange again; clicking pill boxes scrolls to associated filter and opens them if closed.
=> Jo 490 filter nav improvements

docs/tool/css/filters.css, docs/tool/css/styles.css, docs/tool/js/views/filter-view.js, docs/tool/js/views/map-view.js, docs/tool/partials/map-view.html
This PR suggests change the UI display of how filters are scrolled and how the pillboxes appear. For review.
Instead of the entire sidebar scroll, in effect moving the zone-type selectors and the active-filter pillboxes out of view, only the inner container scrolls:
Zonetype descriptions are title text that appear on hover rather than static, where they took up valuable real estate.
Pillboxes fly to a position over the map but only appear when that area is hovered over. We had similar positions in earlier version and opted against it, but I think other changes made since then make this preferable:
Opening filter accordions or clicking on their pillboxes scrolls the filter to the top of the container:
=> WIP: Jo ui suggestions

docs/tool/css/project.css, docs/tool/index.html, docs/tool/js/charts/D3Table.js, docs/tool/js/views/project-view.js, docs/tool/partials/project-view/ownership.html, docs/tool/partials/project-view/saleActivity.html, docs/tool/partials/project-view/subsidy.html, docs/tool/partials/project-view/units.html, docs/tool/test_tabulate.html
Adds a D3Table to the charts section. This reusable chart takes data in the form of an array of objects (standard json representation of tabular data) and turns it into an html table with appripriate `<thead>`, `<tbody><tr><td>` and `<tfooter>` elements. Users can specify which columns should be shown, and a formatting function to be applied to the data for use in number formatting, adding $ , etc. 
Updating the column list or the data and running the `update()` command on the table appropriately adds/removes columns and rows to the data. 
Adds several tables to the project-view using this reusable chart and the existing filter endpoint.
=> 502 tabulate chart

python/housinginsights/tools/misc.py, python/tests/test_tools_misc.py
Updated 'get_unique_addresses_from_str()' to handle the following cases noted in #496:
- incomplete use of dash address
- comma separated numbers
- mixing of commas and & for numbers
- mixing of commas and dash separated numbers with &
- different meaning of &
- cleanly handles cases that may be considered invalid address: logs as invalid and returns original string
Review cases in unit test, run to confirm all tests pass. Add additional test cases if I missed any edge cases and run unit test.
=> 496 - Additional address format parsing

docs/tool/css/styles.css, docs/tool/js/core/router.js, docs/tool/js/views/map-view.js, docs/tool/js/views/results-view.js, docs/tool/partials/map-view.html
— Fixes color coding not loading on URL decode
— Encodes/decodes navBar.right = buildings status
— Encodes/decodes previewBuilding
Third item got complicated and led to other things:
— checks that project layers have in fact been rendered before initializing the url decoding. That was the source of the timing issues
— marks the previewBuilding dot with a red ring
— changes legend to match that and to remove last-filter designations
— Zooms to selected previewBuilding and disables zoom-to-fit-filter-results functionality when there is a previewBuilding selected. It felt like unwanted behavior to have the map zoom away from a selected project. (TO DO: add a way to unselect the previewBuilding)
— scrolls the matching projects list to show the previewBuilding list item (if it matches …
=> Jo 501 finalize url encoding

docs/_includes/header-includes.html, docs/_includes/tool-footer.html, docs/_includes/tool-header.html, docs/_layouts/toolLayout.html, docs/css/main.css, docs/tool/css/styles.css, docs/tool/index.html, docs/tool/js/core/router.js, docs/tool/js/views/filter-view.js, docs/tool/js/views/results-view.js
Moves the tool/index.html content into a toolLayout.html and adds yaml front matter so that the tool is rendered via Jekyl
Fixes various CSS problems due to the conflict caused when the main.css and other sitewide files were introduced
Removes a few console.log statements to speed up performance.
=> Move tool to Jekyll

docs/resources/onboarding/front-end.md
As @NealHumphrey and I talked about at the CodeForDC hacknight --- troubleshooting instructions for the Jekyll installs.
=> Add troubleshooting docs for Mac

python/housinginsights/ingestion/Cleaners.py, python/housinginsights/ingestion/DataReader.py, python/housinginsights/ingestion/LoadData.py, python/housinginsights/ingestion/SQLWriter.py, python/housinginsights/ingestion/functions.py, python/housinginsights/sources/DCHousing.py, python/housinginsights/sources/base.py, python/housinginsights/sources/cama.py, python/housinginsights/sources/census.py, python/housinginsights/sources/dhcd.py, python/housinginsights/sources/google_maps.py, python/housinginsights/sources/mar.py, python/housinginsights/sources/opendata.py, python/housinginsights/sources/prescat.py, python/housinginsights/sources/wmata_distcalc.py, python/housinginsights/tools/logger.py, python/scripts/experimental.py, python/scripts/load_data.py
-Removes the logging level from the init params of the logger, resulting in the use of the default. This lets us specify the logging level in just one place. Set new level to info instead of debug.
- Remove all references to 'logging' so that a second stream handler is not created, making the logging easier to read.
- Adds a counter to the cleaner since debug level messages are no longer shown.
=> Clean up logging

docs/tool/index.html, docs/tool/js/views/map-view.js
Addresses #499 and #501 
I've added a button to the Export CSV modal that copies to the clipboard a list of the names of active filters.
An alternative approach would have been to list the names of the filters directly within the modal. Since the modal already presents the names and values of filters as a table, I didn't want to double the on-screen real estate of the filter titles.
Since the functionality of the D3 Export CSV button comes from some D3-style procedural code inside addExportButton (within map-view.js), I've put the code for the 'copy filter titles' button there.
=> 499 Add 'copy filter names' button

python/housinginsights/ingestion/LoadData.py, python/housinginsights/sources/cama.py, python/scripts/manifest.csv, python/scripts/meta.json
- Calculates residential_units from mar table.
- Records sums in zone_facts table.
- Removes zone_housingunits... row from manifest.csv.
- Marks cama.py as deprecated.
- Removes unused _add_building_permits_rate().
=> Passes sums of residential_units (by zone) to other LoadData methods.

python/housinginsights/ingestion/DataReader.py, python/housinginsights/ingestion/LoadData.py
This takes a few steps towards making our data loading process more robust
- Adds a "debug" mode to the LoadData class (in the __init__ params). If debug mode is true, errors are raised when they occur.
- Wraps the row-level cleaning in a try/except function; if it fails, write an error to the logs, and if in debug mode reraise the error
- Stronger warning (logger.error) when data can't be deleted from the database, and raises the exception if in debug mode. @pfjel7 this would help alert you to the problem that you encountered of an open connection preventing dropping of the table and ending up with duplicate rows. Not complete though - we should work more on this so that it prevents the new data from coming in if the data couldn't be dropped. 
- Moves the deletion of data to occur after …
=> Error handling and moving drop data until after cleaning

python/housinginsights/sources/base.py, python/housinginsights/sources/base_project.py, python/housinginsights/sources/dhcd.py, python/housinginsights/sources/models/dhcd.py, python/housinginsights/tools/dbtools.py
Fixes the issue that the "dhcd_dfd_projects" table, which contains loan information, was returning empty. This was due to an error returned from quickbase that the query was too large. Fixed by only requesting default fields for now, and made note for future users that all fields could be obtained by chunking the request.
Also started making progress towards the reporting / QA task for verifying we are properly matching records. Added a 'found_via' parameter to the _get_nlihc_id_from_db method, telling how the element was identified, as well as the list of all the mar_ids that it found using the addresses. Set up useless function that when finished can use these mar_ids to geocode the project so that it doesn't need to be done during hte cleaning step.
TODO:
- map the fields of the …
=> WIP fixing DHCD data download

docs/tool/js/core/router.js, docs/tool/js/views/filter-view.js, docs/tool/js/views/map-view.js
Several minor bug fixes:
- REAC date slider now init's properly w/ left slider at extreme left
- Clear filters button now works when the only filtering is the unchecked null checkbox
- Several cleanups to the clearing of the previewBuilding (note this is incomplete, need to remove from URLS). 
@ostermanj I left a TODO in router.js at around line 47 - that is the spot that we need to remove the previewBuilding from the url if the data is null. I wasn't sure how to do that properly and it'd likely be faster for you to make the quick fix. Can you take a look?
=> 540 578 slider fixes plus clear selected project fixes

docs/tool/js/views/dataChoices.js
Converts building permit data layers to be the rate versions now availalbe from the api
Adds three new fields that are in the database, but leaves them commented out because the API Flask code needs to be updated per #585 - waiting to deploy new flask code until after the DHCD demo in case the deploy doesn't work properly.
=> Add some new front end fields to data choices

docs/_layouts/home.html, docs/index.html
Changed the website copy of the home page of housinginsights.org in preparation of launch. Changed the buttons in the _layouts/home.html to a single call-to-action to explore the tool. Removed the 'get updates' button in the 'Get involved: Affordable Housing Professionals
=> New Website Copy in Preparation for Launch

python/housinginsights/tools/misc.py
In misc.py check_mar_for_address() we were return the address id result from mar api call as integer and using that for dedupe process for *_addre.csv. This was primarily occurring for dhcd raw data since it isn't processed with any address id metadata. Simply cast it as str type before returning the result.
Run get_api_data on dhcd unique data id and verify that all mar ids are string. Example is 1354 Euclid St.
Since we're already calling mar api to get mar id for missing projects, we should go ahead and store that value in the output.csv (_project.csv & _addre.csv) instead of making another api call when we do geocode clean up in the cleaner code. I'll create a ticket to expand on this further.
=> 583 - made sure mar id is returned as str type and not as integer

docs/data/index.md
It's a trivial issue, but I noticed the link for the tax documentation page wasn't working correctly.  This PR is just a quick fix.
=> fixed type in tax documentation link
